version: '3.9'

services:
  web-app:
    build: .
    image: anilag/web-app:v1
    ports: 
      - 3000:3000
    networks:
      - mongo
    depends_on:
      - mongodb
      - mongo-ui

  mongodb:
    image: mongo
    ports: 
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes: 
      - mongo-data:/data/db
    networks:
      - mongo


  mongo-ui:
    image: mongo-express
    restart: always
    ports:
      - 8085:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_URL=mongodb://admin:pass@mongodb:27017/
      - ME_CONFIG_BASICAUTH=false
    networks: 
      - mongo

volumes:
  mongo-data:
    driver: local

networks:
  mongo:
    name: mongo-network
    driver: bridge
